stages:
  - prepare
  - test
  - deploy
prepare:
  stage: prepare
  script:
    - docker build -t registry.nikamiass.ru/crm:$CI_BUILD_REF_NAME .
test:
  script:
    - docker run -t registry.nikamiass.ru/crm:$CI_BUILD_REF_NAME node_modules/.bin/mocha
  allow_failure: false
deploy:
  stage: deploy
  script:
    - docker push registry.nikamiass.ru/crm:$CI_BUILD_REF_NAME
  when: on_success
