image: docker:latest

services:
  - docker:dind
stages:
  - prepare
  - test
  - deploy

prepare:
  stage: prepare
  script:
    - docker build --file="$CI_BUILD_REF_NAME" -t registry.nikamiass.ru/crm:$CI_BUILD_REF_NAME .
test:
  script:
    - export NODE_ENV=TEST
    - docker run -i -e "NODE_ENV=TEST" registry.nikamiass.ru/crm:$CI_BUILD_REF_NAME node_modules/.bin/mocha
  allow_failure: false
deploy:
  stage: deploy
  script:
    - docker push registry.nikamiass.ru/crm:$CI_BUILD_REF_NAME
  when: on_success
